### ISSUE TITLE
Thanks for maintaining this!

### ISSUE THREAD

**Issue by sffc** [fantasticfears/icu4r#1]
Hi there,

This is Shane from the ICU team.  I wanted to say thank you for supporting this ICU wrapper for Ruby!  I was writing in Ruby today and was glad to find that a wrapper already existed.  If you aren't already subscribed, I encourage you to join the mailing lists icu-announce (low traffic) and icu-design (medium traffic) to keep updated with the latest developments:

http://site.icu-project.org/contacts

**Comment by sffc** [comment]
Good idea.  Done.  The "ICU4R" link that was on there before seems to have been dead.

**Comment by fantasticfears** [comment]
I think it's way early and complete. But Ruby (MRI) changed a lot ever since
